AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple Lambda function

Parameters:
  Environment:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - production

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      CodeUri: .
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /hello
            Method: get
